# Site settings
author: Braydon Janecek
title: Braydon Janecek's Professional Blog
header-img: img/home-bg.png
email: braydoncharlesjanecek@gmail.com
copyright_name: Braydon Janecek
description: > # this means to ignore newlines until "baseurl:"
  Data Science Explored
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bcjanecek

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
